basePath: /
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /hello-world:
    get:
      consumes:
      - application/json
      description: Return Hello world
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Test Swagger with hello world
      tags:
      - Users
  /login:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: login
      tags:
      - Authentication
  /register:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: register
      tags:
      - Authentication
swagger: "2.0"
