basePath: /
definitions:
  responses.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: pratchayaworks@gmail.com
    name: Pratchaya Saenphoi
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Fiber Example API
  version: "1.0"
paths:
  /auth/current-user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: แสดงข้อมูลของผู้ใช้
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - in: query
        name: email
        type: string
      - in: query
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      summary: ลงชื่อเข้าใช้งานระบบ
  /auth/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      summary: ออกจากการใช้งานระบบ
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - in: query
        name: email
        type: string
      - in: query
        name: name
        type: string
      - in: query
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      summary: สมัครเข้าใช้งานระบบ
  /users/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: แสดงข้อมูลผู้ใช้งานทั้งหมดในระบบ
securityDefinitions:
  bearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
